using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace BoardGames.Infraestructure.Migrations
{
    /// <inheritdoc />
    public partial class EffectManadeCardsstaticValue : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "EffectManade",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Question = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    EffectManadeType = table.Column<int>(type: "int", nullable: false),
                    CreatedByUserId = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    IsActive = table.Column<bool>(type: "bit", nullable: false),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_EffectManade", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "EffectManade",
                columns: new[] { "Id", "CreatedAt", "CreatedByUserId", "EffectManadeType", "IsActive", "IsDeleted", "Question" },
                values: new object[,]
                {
                    { 1, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual a melhor raça de cachorro?" },
                    { 2, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o instrumento mais fácil de aprender?" },
                    { 3, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma cidade brasileira que começa com a letra 'B'" },
                    { 4, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva um dos Sete Pecados Capitais" },
                    { 5, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o menor animal que poderia carregar uma mala?" },
                    { 6, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o mlehor brinquedo de um parque de diversão?" },
                    { 7, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Depois de quantos dias você desiste de comer o que sobrou da pizza?" },
                    { 8, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma parte do corpo que todo mundo só tem uma?" },
                    { 9, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de um rapper" },
                    { 10, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva uma criatura do mar que você não comeria" },
                    { 11, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quais dos milagres de Jesus você gostaria de poder realizar?" },
                    { 12, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor nome para uma vaca?" },
                    { 13, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quantos pares de sapato uma pessoa comum deve ter?" },
                    { 14, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma coisa que crianças odeiam comer" },
                    { 15, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga alguma coisa que traz sorte" },
                    { 16, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma bebida que começa com a letra 'C'" },
                    { 17, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Que outro nome este jogo poderia ter?" },
                    { 18, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de uma boneca famosa?" },
                    { 19, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você preferiria ser raptrado por alienígenas, piratas ou fantasmas?" },
                    { 20, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva o nome de uma Maria famosa?" },
                    { 21, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual a pior marca de carro?" },
                    { 22, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma coisa que causa alergia nas pessoas" },
                    { 23, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quantas latas de Coca-cola uma pessoa comum pode beber em um dia?" },
                    { 24, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor sobremesa?" },
                    { 25, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor serviço de streaming de TV?" },
                    { 26, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor feriado brasileiro?" },
                    { 27, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "De todos os animais do mundo, qual é o mais fofo?" },
                    { 28, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o maior animal que você pode derrotar com as próprias mãos?" },
                    { 29, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você preferiria ter uma estátua ou pintura sua?" },
                    { 30, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a sua estação favorita?" },
                    { 31, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor formato de macarrão" },
                    { 32, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de um dragão famoso" },
                    { 33, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de uma criatura mítica" },
                    { 34, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você tivesse uma máquina do tempo, visitaria o passado ou o futuro" },
                    { 35, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a rede de fast food com as melhores batatinhas fritas?" },
                    { 36, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a sua parte favorita do rosto humano?" },
                    { 37, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor superpoder?" },
                    { 38, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de um João famoso" },
                    { 39, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva uma coisa que você pode pôr em conserva" },
                    { 40, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma coisa que você usaria para decorar sua árvode de Natal?" },
                    { 41, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor esporte para se tornar sua profissão?" },
                    { 42, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você preferirira ser qual tipo de árvore?" },
                    { 43, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva um tipo de feijão" },
                    { 44, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Um urso corre na sua direção. O que você faz?" },
                    { 45, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga um animal da fazenda que você não gostaria de comer?" },
                    { 46, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor jeito de preparar um ovo?" },
                    { 47, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor bebida com café?" },
                    { 48, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "O que é mais assustador? altura, aranha, ou falar em público?" },
                    { 49, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você preferirira ter um corpo muito quente ou muito frio?" },
                    { 50, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se vocÊ fosse um professor, qual seria a matéria mais fácil de ensinar para as crianças?" },
                    { 51, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga um legume que começa com a letra 'C'" },
                    { 52, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor serviço de streaming de TV?" },
                    { 53, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Com quantos anos você acha que a maioria das pessoas dá o primeiro beijo?" },
                    { 54, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor bebida quente?" },
                    { 55, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual animal selvagem brasileiro seria o melhor mascote?" },
                    { 56, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual o melhor personagem de How I Met Your Mother?" },
                    { 57, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor aula de ciências: física, química ou biologia?" },
                    { 58, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma marca que começa com a letra A." },
                    { 59, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor condimento?" },
                    { 60, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga um passaro que não voa?" },
                    { 61, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga um filme de terro famoso?" },
                    { 62, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma coisa que você pode pegar emprestada com um vizinho?" },
                    { 63, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse ter mais um olho em outra parte do corpo, onde seria?" },
                    { 64, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor carboidrato: arroz, batata, macarrão ou pão?" },
                    { 65, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o seu som corporal favorito?" },
                    { 66, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Até que horas o café da manhã ainda pode ser considerado café da manhã?" },
                    { 67, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga um planeta do nosso sistema solar. (Exceto a terra)" },
                    { 68, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a princesa da Disney mais casca-grossa?" },
                    { 69, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a banda brasileira mais famosa?" },
                    { 70, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor recheio de sanduíche?" },
                    { 71, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor filme de Star Wars?" },
                    { 72, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor sabor de sorvete?" },
                    { 73, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de uma criatura que bebe sangue?" },
                    { 74, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Faça o som que um animal faz" },
                    { 75, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma comida que tem um buraco" },
                    { 76, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma trilogia de filmes." },
                    { 77, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse fazer parte da primeira colônia de humanos em Marte (mas nunca voltar para a Terra), você iria?" },
                    { 78, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a pior parte de uma salada?" },
                    { 79, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva o nome de um urso de desenho animado." },
                    { 80, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se todos vocês fossem ratos, quem seria o primeiro a ser comido por um gato?" },
                    { 81, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual arma você escoheria para um duelo?" },
                    { 82, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor tipo de biscoito?" },
                    { 83, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma das ferramentas de um canivete suíço" },
                    { 84, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de um robõ famoso." },
                    { 85, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "O que deixa um bafo pior: cebola, alho ou café?" },
                    { 86, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de uma boy band famosa." },
                    { 87, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor tipo de 'fezes' de animal para pisar?" },
                    { 88, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quem neste cômodo tem mais chance de entrar no Paraíso?" },
                    { 89, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quem neste cômodo tem mais chance de entrar no Inferno?" },
                    { 90, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse ser um especialista em um instrumento musical, qual escolheria" },
                    { 91, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "VocÊ preferiria ter o corpo coberto de penas ou de pelo" },
                    { 92, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você preferiria entender os animais ou que os animais entendessem você?" },
                    { 93, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o pior dia útil" },
                    { 94, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor serviço de streaming de TV?" },
                    { 95, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "O certo é abrir os presentes de Natal antes ou depois da véspera de Natal" },
                    { 96, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você rolou um dado. Qual número saiu?" },
                    { 97, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse fazer parte de uma família da ficção, qual seria?" },
                    { 98, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quem venceria uma luta de boxe entre Anderson Silva, Mike Tyson, Popó e Davi Brito?" },
                    { 99, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse ter o cabelo de qualquer cor, qual escolheria?" },
                    { 100, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você está usando uma camisa branca novinha. De qual comida é melhor passar longe?" },
                    { 101, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma coisa que você guarda no bolso de trás" },
                    { 102, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma coisa que você pode encontrar na praia." },
                    { 103, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quem você traria de volta dos mortos: Einstein, Shakespeare ou Mozart" },
                    { 104, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de um dos Sete Anões" },
                    { 105, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se tivesse que escolher pratos de apenas um país para comer pelo resto da vida, qual seria?" },
                    { 106, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor sabor de pipoca: doce, salgada ou meio a meio?" },
                    { 107, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o seu dedo favorito?" },
                    { 108, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você tivesse inventado a torradeira, mas não quisesse que ela tivesse esse nome, qual seria o nome dela?" },
                    { 109, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a sua moeda favorita abaixo de R$ 1,00" },
                    { 110, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse escolher um dia para se repetir para sempre, seria: Natal, Dia das Bruxas ou seu aniversário?" },
                    { 111, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o gênero musical mais irritante?" },
                    { 112, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva o nome de um bruxo famoso." },
                    { 113, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva um país que começa com a letra B?" },
                    { 114, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva um animal com quatro letras." },
                    { 115, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quantas horas tem uma noite de sono perfeita" },
                    { 116, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você só tem 10 minutos para fazer sua fantasia de Dia das Bruxas. De que você vai se vestir?" },
                    { 117, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o animal mais rápido sem pernas?" },
                    { 118, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse ganhar uma dessas opções, qual seria: Oscar, Medalha Olímpica ou Prêmio Nobel?" },
                    { 119, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a sua refeição favorita do dia" },
                    { 120, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de um rato da ficção" },
                    { 121, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Quantos Big Macs alguém consegue comer em 20 minutos?" },
                    { 122, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a comida mias grudenta?" },
                    { 123, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é seu dinossauro favorito? (exceto o Tiranossauro Rex)" },
                    { 124, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga um tipo de chapéu" },
                    { 125, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o pior crime: jogar lixo na rua, cuspir ou sempre se atrasar?" },
                    { 126, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "De qual programa competitivo você participaria?" },
                    { 127, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse falar gatês, o que 'miau' significaria?" },
                    { 128, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor comida para comer doente?" },
                    { 129, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a pior mania: cutucar o nariz, falar de boca cheia ou roer as unhas?" },
                    { 130, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a primeira coisa que você faz de manhã?" },
                    { 131, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o seu animal australiano favorito?" },
                    { 132, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual bichinho rastejante daria a melhor mascote?" },
                    { 133, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você prefere ir num rodízio de comida japonesa ou de churrasco?" },
                    { 134, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva alguma coisa que você pode preparar no micro-ondas?" },
                    { 135, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual Presidente do Brasil você mais gostaria de conhecer?" },
                    { 136, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor sabor de pizza?" },
                    { 137, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor jeito de preparar uma batata: purê, gratinada ou frita?" },
                    { 138, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga um país muito quente." },
                    { 139, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Pedra, Papel ou Tesoura?" },
                    { 140, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você está em um restaurante e precisa escolher entre um brigadeiro ou um pudim. O que você escolhe?" },
                    { 141, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma parte do corpo de uma vaca." },
                    { 142, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor filme de Natal?" },
                    { 143, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "De todos os animais no mundo, qual é o mais forte?" },
                    { 144, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você acabou de adotar um bebê iéti. Qual será o nome dele?" },
                    { 145, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "De todos os jogadores, quem está com a melhor roupa hoje?" },
                    { 146, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você pudesse ser um animal da fazenda qual seria?" },
                    { 147, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva a maior furta que cabe na sua boca sem que você precise cortar primeiro" },
                    { 148, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva um animal que começa com a letra P." },
                    { 149, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva um instrumento musical que você pode colocar no seu bolso" },
                    { 150, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor filme da Disney de todos os tempos?" },
                    { 151, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma coisa roxa." },
                    { 152, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor sabor de salgadinho?" },
                    { 153, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma coisa que você faz antes de dormir." },
                    { 154, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o maior objeto com rodas que você consegue levantar?" },
                    { 155, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de um anti-herói famoso." },
                    { 156, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva uma palavara que começa com a letra Z." },
                    { 157, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva o nome de um país frio." },
                    { 158, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor cômodo da casa?" },
                    { 159, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de algo vendido na padaria." },
                    { 160, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Vcoê preferiria comer uma coisa salgada demais ou doce demais?" },
                    { 161, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor tipo de pizza: crocante, macia, ou com borda recheada?" },
                    { 162, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma fruta que deve ser difícil de usar em malabarismo." },
                    { 163, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual letra não faria falta se fosse removida do alfabeto?" },
                    { 164, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a coisa mais escorregadia do mundo?" },
                    { 165, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "O que um caracol guarda na concha?" },
                    { 166, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o pior legume?" },
                    { 167, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o mês do ano mais difícil de soletrar?" },
                    { 168, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga alguma coisa que assustaria um cachorro." },
                    { 169, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma comida que você comeria no Natal." },
                    { 170, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "O que você deve vestir primeiro: roupa íntima ou meias?" },
                    { 171, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o esporte mais chato de assistir?" },
                    { 172, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor marca de tênis?" },
                    { 173, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você preferiria ter um olho gigante ou uma orelha enorme?" },
                    { 174, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva alguma coisa que vem em pares." },
                    { 175, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor cerela para o café da manhã?" },
                    { 176, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual invenção você gostaria de destruir?" },
                    { 177, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga o nome de uma pessoa ruiva famosa" },
                    { 178, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você preferiria ser a pessoa mais rica ou mais esperta do mundo?" },
                    { 179, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor personagem do Chaves?" },
                    { 180, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga uma comida que você não precisa mastigar." },
                    { 181, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva uma banda qwue começa com a letra R" },
                    { 182, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o legume ou fruta mais pesado?" },
                    { 183, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor cor de roupa íntima?" },
                    { 184, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o evento mais inútil das Olimpíadas?" },
                    { 185, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva um país que fala espanho que não é a Espanha." },
                    { 186, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga um animal que não tem rabo." },
                    { 187, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você pode ser um animal que vive embaixo d'água. Qual você quer ser?" },
                    { 188, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor cor de M&M?" },
                    { 189, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Escreva um trabalho que começa com a letra B." },
                    { 190, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se vocÊ tivesse que escolher, qual parte do seu corpo seria picada por uma vespa?" },
                    { 191, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é a melhor utensílio de cozinha?" },
                    { 192, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "O melhor leite é: desnatado, semidesnatado, integral ou zero lactose?" },
                    { 193, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Você preferiria falar como o Yoda ou como o Darth Vader?" },
                    { 194, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "As personalidades das pessoas dependem do signo do zodíaco?" },
                    { 195, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Se você tivesse que escolher outro nome para a pessoa lendo esta carta de tema, qual seria?" },
                    { 196, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Diga alguma coisa que você pode levar para o banho." },
                    { 197, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qaul é o aplicativo mais útil do celular?" },
                    { 198, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o pior rede de fast food?" },
                    { 199, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "O que vocÊ pode comer e também usar como calçado?" },
                    { 200, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Uma pessoa aposta R$ 1 milhão na roleta. Ela pede seu conselho vermelho ou preto?" },
                    { 201, new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc), "MICAEL", 0, true, false, "Qual é o melhor restaurante de fast food?" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "EffectManade");
        }
    }
}
