using BoardGames.Domain.EffectManade;
using Microsoft.EntityFrameworkCore;

namespace BoardGames.Infraestructure.DbContext;

public class BoardGameDbContext(DbContextOptions<BoardGameDbContext> options) : Microsoft.EntityFrameworkCore.DbContext(options)
{
    public DbSet<EffectManadeCardDB> EffectManade => Set<EffectManadeCardDB>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        var seedDate = new DateTime(2024, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        modelBuilder.Entity<EffectManadeCardDB>()
            .HasData(
                new EffectManadeCardDB { Id = 1,  Question = "Qual a melhor raça de cachorro?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 2,  Question = "Qual é o instrumento mais fácil de aprender?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 3,  Question = "Diga uma cidade brasileira que começa com a letra 'B'", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 4,  Question = "Escreva um dos Sete Pecados Capitais", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 5,  Question = "Qual é o menor animal que poderia carregar uma mala?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 6,  Question = "Qual é o mlehor brinquedo de um parque de diversão?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 7,  Question = "Depois de quantos dias você desiste de comer o que sobrou da pizza?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 8,  Question = "Diga uma parte do corpo que todo mundo só tem uma?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 9,  Question = "Diga o nome de um rapper", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 10, Question = "Escreva uma criatura do mar que você não comeria", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 11, Question = "Quais dos milagres de Jesus você gostaria de poder realizar?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 12, Question = "Qual é o melhor nome para uma vaca?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 13, Question = "Quantos pares de sapato uma pessoa comum deve ter?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 14, Question = "Diga uma coisa que crianças odeiam comer", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 15, Question = "Diga alguma coisa que traz sorte", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 16, Question = "Diga uma bebida que começa com a letra 'C'", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 17, Question = "Que outro nome este jogo poderia ter?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 18, Question = "Diga o nome de uma boneca famosa?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 19, Question = "Você preferiria ser raptrado por alienígenas, piratas ou fantasmas?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 20, Question = "Escreva o nome de uma Maria famosa?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 21, Question = "Qual a pior marca de carro?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 22, Question = "Diga uma coisa que causa alergia nas pessoas", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 23, Question = "Quantas latas de Coca-cola uma pessoa comum pode beber em um dia?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 24, Question = "Qual é a melhor sobremesa?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 25, Question = "Qual é a melhor serviço de streaming de TV?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 26, Question = "Qual é o melhor feriado brasileiro?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 27, Question = "De todos os animais do mundo, qual é o mais fofo?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 28, Question = "Qual é o maior animal que você pode derrotar com as próprias mãos?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 29, Question = "Você preferiria ter uma estátua ou pintura sua?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 30, Question = "Qual é a sua estação favorita?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 31, Question = "Qual é o melhor formato de macarrão", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 32, Question = "Diga o nome de um dragão famoso", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 33, Question = "Diga o nome de uma criatura mítica", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 34, Question = "Se você tivesse uma máquina do tempo, visitaria o passado ou o futuro", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 35, Question = "Qual é a rede de fast food com as melhores batatinhas fritas?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 36, Question = "Qual é a sua parte favorita do rosto humano?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 37, Question = "Qual é o melhor superpoder?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 38, Question = "Diga o nome de um João famoso", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 39, Question = "Escreva uma coisa que você pode pôr em conserva", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 40, Question = "Diga uma coisa que você usaria para decorar sua árvode de Natal?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 41, Question = "Qual é o melhor esporte para se tornar sua profissão?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 42, Question = "Você preferirira ser qual tipo de árvore?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 43, Question = "Escreva um tipo de feijão", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 44, Question = "Um urso corre na sua direção. O que você faz?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 45, Question = "Diga um animal da fazenda que você não gostaria de comer?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 46, Question = "Qual é o melhor jeito de preparar um ovo?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 47, Question = "Qual é a melhor bebida com café?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 48, Question = "O que é mais assustador? altura, aranha, ou falar em público?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 49, Question = "Você preferirira ter um corpo muito quente ou muito frio?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 50, Question = "Se vocÊ fosse um professor, qual seria a matéria mais fácil de ensinar para as crianças?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 51, Question = "Diga um legume que começa com a letra 'C'", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 52, Question = "Qual é a melhor serviço de streaming de TV?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 53, Question = "Com quantos anos você acha que a maioria das pessoas dá o primeiro beijo?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 54, Question = "Qual é a melhor bebida quente?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 55, Question = "Qual animal selvagem brasileiro seria o melhor mascote?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 56, Question = "Qual o melhor personagem de How I Met Your Mother?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 57, Question = "Qual é a melhor aula de ciências: física, química ou biologia?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 58, Question = "Diga uma marca que começa com a letra A.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 59, Question = "Qual é o melhor condimento?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 60, Question = "Diga um passaro que não voa?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 61, Question = "Diga um filme de terro famoso?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 62, Question = "Diga uma coisa que você pode pegar emprestada com um vizinho?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 63, Question = "Se você pudesse ter mais um olho em outra parte do corpo, onde seria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 64, Question = "Qual é o melhor carboidrato: arroz, batata, macarrão ou pão?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 65, Question = "Qual é o seu som corporal favorito?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 66, Question = "Até que horas o café da manhã ainda pode ser considerado café da manhã?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 67, Question = "Diga um planeta do nosso sistema solar. (Exceto a terra)", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 68, Question = "Qual é a princesa da Disney mais casca-grossa?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 69, Question = "Qual é a banda brasileira mais famosa?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 70, Question = "Qual é o melhor recheio de sanduíche?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 71, Question = "Qual é o melhor filme de Star Wars?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 72, Question = "Qual é o melhor sabor de sorvete?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 73, Question = "Diga o nome de uma criatura que bebe sangue?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 74, Question = "Faça o som que um animal faz", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 75, Question = "Diga uma comida que tem um buraco", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 76, Question = "Diga uma trilogia de filmes.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 77, Question = "Se você pudesse fazer parte da primeira colônia de humanos em Marte (mas nunca voltar para a Terra), você iria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 78, Question = "Qual é a pior parte de uma salada?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 79, Question = "Escreva o nome de um urso de desenho animado.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 80, Question = "Se todos vocês fossem ratos, quem seria o primeiro a ser comido por um gato?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 81, Question = "Qual arma você escoheria para um duelo?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 82, Question = "Qual é o melhor tipo de biscoito?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 83, Question = "Diga uma das ferramentas de um canivete suíço", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 84, Question = "Diga o nome de um robõ famoso.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 85, Question = "O que deixa um bafo pior: cebola, alho ou café?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 86, Question = "Diga o nome de uma boy band famosa.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 87, Question = "Qual é o melhor tipo de 'fezes' de animal para pisar?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 88, Question = "Quem neste cômodo tem mais chance de entrar no Paraíso?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 89, Question = "Quem neste cômodo tem mais chance de entrar no Inferno?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 90, Question = "Se você pudesse ser um especialista em um instrumento musical, qual escolheria", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 91, Question = "VocÊ preferiria ter o corpo coberto de penas ou de pelo", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 92, Question = "Você preferiria entender os animais ou que os animais entendessem você?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 93, Question = "Qual é o pior dia útil", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 94, Question = "Qual é a melhor serviço de streaming de TV?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 95, Question = "O certo é abrir os presentes de Natal antes ou depois da véspera de Natal", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 96, Question = "Você rolou um dado. Qual número saiu?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 97, Question = "Se você pudesse fazer parte de uma família da ficção, qual seria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 98, Question = "Quem venceria uma luta de boxe entre Anderson Silva, Mike Tyson, Popó e Davi Brito?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 99, Question = "Se você pudesse ter o cabelo de qualquer cor, qual escolheria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 100, Question = "Você está usando uma camisa branca novinha. De qual comida é melhor passar longe?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 101, Question = "Diga uma coisa que você guarda no bolso de trás", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 102, Question = "Diga uma coisa que você pode encontrar na praia.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 103, Question = "Quem você traria de volta dos mortos: Einstein, Shakespeare ou Mozart", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 104, Question = "Diga o nome de um dos Sete Anões", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 105, Question = "Se tivesse que escolher pratos de apenas um país para comer pelo resto da vida, qual seria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 106, Question = "Qual é o melhor sabor de pipoca: doce, salgada ou meio a meio?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 107, Question = "Qual é o seu dedo favorito?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 108, Question = "Se você tivesse inventado a torradeira, mas não quisesse que ela tivesse esse nome, qual seria o nome dela?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 109, Question = "Qual é a sua moeda favorita abaixo de R$ 1,00", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 110, Question = "Se você pudesse escolher um dia para se repetir para sempre, seria: Natal, Dia das Bruxas ou seu aniversário?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 111, Question = "Qual é o gênero musical mais irritante?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 112, Question = "Escreva o nome de um bruxo famoso.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 113, Question = "Escreva um país que começa com a letra B?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 114, Question = "Escreva um animal com quatro letras.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 115, Question = "Quantas horas tem uma noite de sono perfeita", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 116, Question = "Você só tem 10 minutos para fazer sua fantasia de Dia das Bruxas. De que você vai se vestir?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 117, Question = "Qual é o animal mais rápido sem pernas?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 118, Question = "Se você pudesse ganhar uma dessas opções, qual seria: Oscar, Medalha Olímpica ou Prêmio Nobel?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 119, Question = "Qual é a sua refeição favorita do dia", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 120, Question = "Diga o nome de um rato da ficção", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 121, Question = "Quantos Big Macs alguém consegue comer em 20 minutos?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 122, Question = "Qual é a comida mias grudenta?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 123, Question = "Qual é seu dinossauro favorito? (exceto o Tiranossauro Rex)", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 124, Question = "Diga um tipo de chapéu", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 125, Question = "Qual é o pior crime: jogar lixo na rua, cuspir ou sempre se atrasar?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 126, Question = "De qual programa competitivo você participaria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 127, Question = "Se você pudesse falar gatês, o que 'miau' significaria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 128, Question = "Qual é a melhor comida para comer doente?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 129, Question = "Qual é a pior mania: cutucar o nariz, falar de boca cheia ou roer as unhas?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 130, Question = "Qual é a primeira coisa que você faz de manhã?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 131, Question = "Qual é o seu animal australiano favorito?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 132, Question = "Qual bichinho rastejante daria a melhor mascote?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 133, Question = "Você prefere ir num rodízio de comida japonesa ou de churrasco?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 134, Question = "Escreva alguma coisa que você pode preparar no micro-ondas?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 135, Question = "Qual Presidente do Brasil você mais gostaria de conhecer?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 136, Question = "Qual é o melhor sabor de pizza?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 137, Question = "Qual é o melhor jeito de preparar uma batata: purê, gratinada ou frita?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 138, Question = "Diga um país muito quente.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 139, Question = "Pedra, Papel ou Tesoura?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 140, Question = "Você está em um restaurante e precisa escolher entre um brigadeiro ou um pudim. O que você escolhe?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 141, Question = "Diga uma parte do corpo de uma vaca.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 142, Question = "Qual é o melhor filme de Natal?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 143, Question = "De todos os animais no mundo, qual é o mais forte?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 144, Question = "Você acabou de adotar um bebê iéti. Qual será o nome dele?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 145, Question = "De todos os jogadores, quem está com a melhor roupa hoje?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 146, Question = "Se você pudesse ser um animal da fazenda qual seria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 147, Question = "Escreva a maior furta que cabe na sua boca sem que você precise cortar primeiro", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 148, Question = "Escreva um animal que começa com a letra P.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 149, Question = "Escreva um instrumento musical que você pode colocar no seu bolso", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 150, Question = "Qual é o melhor filme da Disney de todos os tempos?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 151, Question = "Diga uma coisa roxa.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 152, Question = "Qual é o melhor sabor de salgadinho?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 153, Question = "Diga uma coisa que você faz antes de dormir.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 154, Question = "Qual é o maior objeto com rodas que você consegue levantar?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 155, Question = "Diga o nome de um anti-herói famoso.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 156, Question = "Escreva uma palavara que começa com a letra Z.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 157, Question = "Escreva o nome de um país frio.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 158, Question = "Qual é o melhor cômodo da casa?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 159, Question = "Diga o nome de algo vendido na padaria.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 160, Question = "Vcoê preferiria comer uma coisa salgada demais ou doce demais?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 161, Question = "Qual é o melhor tipo de pizza: crocante, macia, ou com borda recheada?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 162, Question = "Diga uma fruta que deve ser difícil de usar em malabarismo.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 163, Question = "Qual letra não faria falta se fosse removida do alfabeto?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 164, Question = "Qual é a coisa mais escorregadia do mundo?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 165, Question = "O que um caracol guarda na concha?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 166, Question = "Qual é o pior legume?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 167, Question = "Qual é o mês do ano mais difícil de soletrar?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 168, Question = "Diga alguma coisa que assustaria um cachorro.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 169, Question = "Diga uma comida que você comeria no Natal.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 170, Question = "O que você deve vestir primeiro: roupa íntima ou meias?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 171, Question = "Qual é o esporte mais chato de assistir?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 172, Question = "Qual é a melhor marca de tênis?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 173, Question = "Você preferiria ter um olho gigante ou uma orelha enorme?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 174, Question = "Escreva alguma coisa que vem em pares.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 175, Question = "Qual é o melhor cerela para o café da manhã?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 176, Question = "Qual invenção você gostaria de destruir?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 177, Question = "Diga o nome de uma pessoa ruiva famosa", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 178, Question = "Você preferiria ser a pessoa mais rica ou mais esperta do mundo?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 179, Question = "Qual é o melhor personagem do Chaves?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 180, Question = "Diga uma comida que você não precisa mastigar.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 181, Question = "Escreva uma banda qwue começa com a letra R", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 182, Question = "Qual é o legume ou fruta mais pesado?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 183, Question = "Qual é a melhor cor de roupa íntima?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 184, Question = "Qual é o evento mais inútil das Olimpíadas?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 185, Question = "Escreva um país que fala espanho que não é a Espanha.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 186, Question = "Diga um animal que não tem rabo.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 187, Question = "Você pode ser um animal que vive embaixo d'água. Qual você quer ser?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 188, Question = "Qual é a melhor cor de M&M?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 189, Question = "Escreva um trabalho que começa com a letra B.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 190, Question = "Se vocÊ tivesse que escolher, qual parte do seu corpo seria picada por uma vespa?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 191, Question = "Qual é a melhor utensílio de cozinha?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 192, Question = "O melhor leite é: desnatado, semidesnatado, integral ou zero lactose?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 193, Question = "Você preferiria falar como o Yoda ou como o Darth Vader?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 194, Question = "As personalidades das pessoas dependem do signo do zodíaco?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 195, Question = "Se você tivesse que escolher outro nome para a pessoa lendo esta carta de tema, qual seria?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 196, Question = "Diga alguma coisa que você pode levar para o banho.", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 197, Question = "Qaul é o aplicativo mais útil do celular?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 198, Question = "Qual é o pior rede de fast food?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 199, Question = "O que vocÊ pode comer e também usar como calçado?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 200, Question = "Uma pessoa aposta R$ 1 milhão na roleta. Ela pede seu conselho vermelho ou preto?", CreatedAt = seedDate },
                new EffectManadeCardDB { Id = 201, Question = "Qual é o melhor restaurante de fast food?", CreatedAt = seedDate }
            );
    }
}